# Spring properties
server:
  port : 2081
spring:
  application:
    name: car-service
  data:
    mongodb.host: mongodb
    mongodb.port: 2717
    mongodb.uri: mongodb://localhost:2717/test
    mongo.repositories.enabled: true

javers:
  snapshotCollectionName: "jv_customer_snapshots"
  headCollectionName: "jv_customer_head_id"
  schemaManagementEnabled: false
  snapshotsCacheSize: 5000

